// Plugin-managed agy HOME (B1/B2): the plugin assembles everything agy
// discovers through $HOME — its global rules, its global skills, and the
// reverse MCP bridge config — inside a directory the plugin owns, so the
// user's real ~/.gemini is never read or written.
//
// Verified against the real CLI: agy resolves all of it from $HOME
// (GEMINI_CLI_HOME alone is ignored, and the macOS Keychain is not used).
// Rules live at $HOME/.gemini/GEMINI.md, global skills at
// $HOME/.gemini/config/skills/<name>/SKILL.md, and MCP servers at
// $HOME/.gemini/config/mcp_config.json.
import { chmodSync, copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { dshHome } from '../common/config.ts'
import type { ManagedAccount } from '../common/pool-types.ts'
import { allowMcpServer, mcpConfigPath, mergeMcpConfig, type McpBridge } from './mcp-bridge.ts'
import { defaultPoolDir } from './pool.ts'

/**
 * First line of every generated GEMINI.md. agy has no include mechanism that
 * survives a relocated HOME, so the rules are materialized as a copy — this
 * banner is what tells a human (and agy) that the file is generated.
 */
export const GENERATED_HEADER =
  "<!-- Generated by dsh-agy-link from DSH's global AGENTS.md (~/.dsh/AGENTS.md). Do not edit by hand - edit the DSH file instead. -->"

/**
 * DSH-only surfaces that mean nothing inside agy. Anything referencing them is
 * dropped instead of forwarded: forwarding them makes agy read instructions
 * for tools it does not have (the DSH skill loader, the run_code transport,
 * goal tools, the imagegen plugin, DSH Web lifecycle).
 */
const DSH_ONLY: readonly RegExp[] = [
  /run_code/,
  /todo_write/,
  /dsh-imagegen/i,
  /dsh-ui/i,
  /\bgenui\b/i,
  /dsh[-\s]?web/i,
  /\b(?:create|get|update)_goal\b/,
  /会话目标/,
  /agy_tool/,
  /\b(?:generate|edit)_image\b/,
  /`skill`\s*(?:工具|技能)/,
]

function isDshOnly(line: string): boolean {
  return DSH_ONLY.some((re) => re.test(line))
}

function headingLevel(line: string): number {
  const m = /^(#{1,6})\s+\S/.exec(line)
  return m?.[1]?.length ?? 0
}

/**
 * Adapt DSH's global AGENTS.md into agy's global rules file. Pure: the caller
 * reads the source and writes the result. A line referencing a DSH-only
 * surface is dropped; a HEADING that does so drops its whole section (body
 * included), which is how the DSH skill-loading table and its protocol
 * disappear without leaving an orphaned body behind.
 */
export function adaptAgentsMd(source: string): string {
  const kept: string[] = []
  let dropped = 0
  for (const line of source.split(/\r?\n/)) {
    const level = headingLevel(line)
    if (level > 0) {
      if (dropped > 0 && level > dropped) continue
      dropped = isDshOnly(line) ? level : 0
      if (dropped === 0) kept.push(line)
      continue
    }
    if (dropped > 0) continue
    if (isDshOnly(line)) continue
    kept.push(line)
  }
  const body = kept.join('\n').replace(/\n{3,}/g, '\n\n').trim()
  return GENERATED_HEADER + '\n\n' + body + '\n'
}

const AGY_TOKEN_FILE = join('.gemini', 'antigravity-cli', 'antigravity-oauth-token')

/**
 * HOME the plugin spawns agy with for this account. Isolated pool accounts
 * keep their own directory; the system-HOME account gets a plugin-managed
 * directory so its rules, skills and bridge config never land in the real
 * ~/.gemini (its credential is seeded from there instead).
 *
 * The managed HOME lives INSIDE the pool directory on purpose: pool.json,
 * every isolated account and every managed HOME are then one subtree, so the
 * config-manager sync picks all of them up with a single directory rule
 * instead of two unrelated paths.
 */
export function agyHomeFor(account: ManagedAccount): string {
  if (account.dir !== '') return account.dir
  return join(defaultPoolDir(), 'env', account.id)
}

/**
 * First-use seeding: the system-HOME account's credential is COPIED into the
 * managed HOME (verified safe — agy stays signed in, refreshes only its own
 * copy, and the real HOME's token is left alone). An existing managed token is
 * never overwritten: once the managed HOME refreshes its own token, that copy
 * is the authoritative one.
 */
export function seedAgyHome(home: string, sourceHome: string): void {
  const target = join(home, AGY_TOKEN_FILE)
  if (existsSync(target)) return
  const source = join(sourceHome, AGY_TOKEN_FILE)
  if (!existsSync(source)) return
  mkdirSync(dirname(target), { recursive: true })
  copyFileSync(source, target)
  try {
    chmodSync(target, 0o600)
  } catch {
    // Windows: mode bits unsupported — best effort
  }
}

export interface AgyEnvOptions {
  /** Reverse MCP bridge to publish into the managed HOME; omitted when disabled. */
  bridge?: McpBridge
  /** Real user HOME the managed HOME is seeded from (defaults to the process HOME). */
  sourceHome?: string
}

/**
 * Materialize the plugin-managed agy environment for one account and return
 * its HOME. Idempotent: a file is rewritten only when its bytes change, so the
 * per-spawn call never churns mtimes.
 */
export function syncAgyEnv(account: ManagedAccount, opts: AgyEnvOptions = {}): string {
  const home = agyHomeFor(account)
  // Only a plugin-managed HOME is seeded: an isolated account must never
  // inherit the system credential, or two slots would share one identity.
  if (home !== account.dir) seedAgyHome(home, opts.sourceHome ?? homedir())
  const agents = join(dshHome(), 'AGENTS.md')
  if (existsSync(agents)) {
    writeIfChanged(join(home, '.gemini', 'GEMINI.md'), adaptAgentsMd(readFileSync(agents, 'utf8')))
  }
  copySkills(join(dshHome(), 'skills'), join(home, '.gemini', 'config', 'skills'))
  if (opts.bridge !== undefined) {
    const file = mcpConfigPath(home)
    writeIfChanged(file, mergeMcpConfig(readIfExists(file), opts.bridge))
    // Plan mode is the only mode that consults permissions.allow ('skip', the
    // default, already passes everything). The file is agy's own and is only
    // amended when agy already created it.
    const settings = join(home, '.gemini', 'antigravity-cli', 'settings.json')
    if (existsSync(settings)) {
      const next = allowMcpServer(readFileSync(settings, 'utf8'))
      if (next !== null) writeIfChanged(settings, next)
    }
  }
  return home
}

function readIfExists(file: string): string | null {
  return existsSync(file) ? readFileSync(file, 'utf8') : null
}

/** Write only when the content differs — keeps the whole sync mtime-stable. */
function writeIfChanged(file: string, content: string): void {
  if (readIfExists(file) === content) return
  mkdirSync(dirname(file), { recursive: true })
  writeFileSync(file, content, 'utf8')
}

/** Copy every DSH skill (a directory holding a SKILL.md) into agy's own skill dir. */
function copySkills(source: string, dest: string): void {
  if (!existsSync(source)) return
  for (const entry of readdirSync(source, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    const skill = join(source, entry.name)
    if (!existsSync(join(skill, 'SKILL.md'))) continue
    copyTree(skill, join(dest, entry.name))
  }
}

function copyTree(source: string, dest: string): void {
  mkdirSync(dest, { recursive: true })
  for (const entry of readdirSync(source, { withFileTypes: true })) {
    const from = join(source, entry.name)
    const to = join(dest, entry.name)
    if (entry.isDirectory()) copyTree(from, to)
    else copyFileIfChanged(from, to)
  }
}

function copyFileIfChanged(from: string, to: string): void {
  if (existsSync(to)) {
    const source = statSync(from)
    const target = statSync(to)
    if (source.size === target.size && readFileSync(from).equals(readFileSync(to))) return
  }
  copyFileSync(from, to)
}
