// Plugin-managed agy HOME (B1/B2): the plugin assembles everything agy
// discovers through $HOME — its global skills, its hooks, and the reverse MCP
// bridge config — inside a directory the plugin owns, so the user's real
// ~/.gemini is never read or written.
//
// Verified against the real CLI: agy resolves all of it from $HOME and
// GEMINI_CLI_HOME alone is ignored. It authenticates from that HOME's own
// antigravity-oauth-token file, so a managed HOME is self-contained.
// Global skills live at $HOME/.gemini/config/skills/<name>/SKILL.md, hooks at
// $HOME/.gemini/config/hooks.json, and MCP servers at
// $HOME/.gemini/config/mcp_config.json.
//
// No global rules file is materialized: agy auto-discovers GEMINI.md from
// $HOME/.gemini and $HOME/.gemini/config, so ANY file there would apply to
// every run including subagents. DSH's global rules ride the root run's prompt
// instead (see adapter.ts), which keeps a subagent rule-free.
import { chmodSync, copyFileSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, readlinkSync, rmSync, statSync, symlinkSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { dshHome } from '../common/config.ts'
import type { ManagedAccount } from '../common/pool-types.ts'
import { allowMcpServer, mcpConfigPath, mergeMcpConfig, type McpBridge } from './mcp-bridge.ts'
import { defaultPoolDir } from './pool.ts'

/**
 * First line of the rules text this plugin hands to agy. It carries no file
 * path: the rules travel in the root run's PreInvocation payload (see
 * rootRulesPayload), and a copy on disk would also reach subagent runs. This
 * banner is what tells the model that the text is generated and where its
 * source of truth lives.
 */
export const GENERATED_HEADER =
  "<!-- Generated by dsh-agy-link from DSH's global AGENTS.md (~/.dsh/AGENTS.md). Do not edit by hand - edit the DSH file instead. -->"

/**
 * DSH-only surfaces that mean nothing inside agy. Anything referencing them is
 * dropped instead of forwarded: forwarding them makes agy read instructions
 * for tools it does not have (the DSH skill loader, the run_code transport,
 * goal tools, the imagegen plugin, DSH Web lifecycle).
 */
const DSH_ONLY: readonly RegExp[] = [
  /run_code/,
  /todo_write/,
  /dsh-imagegen/i,
  /dsh-ui/i,
  /\bgenui\b/i,
  /dsh[-\s]?web/i,
  /\b(?:create|get|update)_goal\b/,
  /会话目标/,
  /agy_tool/,
  /\b(?:generate|edit)_image\b/,
  /`skill`\s*(?:工具|技能)/,
]

function isDshOnly(line: string): boolean {
  return DSH_ONLY.some((re) => re.test(line))
}

function headingLevel(line: string): number {
  const m = /^(#{1,6})\s+\S/.exec(line)
  return m?.[1]?.length ?? 0
}

/**
 * Adapt DSH's global AGENTS.md for agy. Pure: the caller reads the source and
 * embeds the result in the PreInvocation payload. A line referencing a DSH-only
 * surface is dropped; a HEADING that does so drops its whole section (body
 * included), which is how the DSH skill-loading table and its protocol
 * disappear without leaving an orphaned body behind.
 */
export function adaptAgentsMd(source: string): string {
  const kept: string[] = []
  let dropped = 0
  for (const line of source.split(/\r?\n/)) {
    const level = headingLevel(line)
    if (level > 0) {
      if (dropped > 0 && level > dropped) continue
      dropped = isDshOnly(line) ? level : 0
      if (dropped === 0) kept.push(line)
      continue
    }
    if (dropped > 0) continue
    if (isDshOnly(line)) continue
    kept.push(line)
  }
  const body = kept.join('\n').replace(/\n{3,}/g, '\n\n').trim()
  return GENERATED_HEADER + '\n\n' + body + '\n'
}

/**
 * PreToolUse gate. agy resolves its own subagents internally, so DSH's
 * delegation-depth cap cannot see them — the only reachable lever is this hook.
 * The allow branch MUST answer `{"decision":"allow"}`: an empty object is not
 * a grant, so a root run would be denied its own delegation.
 */
const SUBAGENT_GATE = `if [ "$DSH_AGY_ALLOW_SUBAGENTS" = "1" ]; then printf %s '{"decision":"allow"}'; else printf %s '{"decision":"deny","reason":"DSH policy: subagent delegation is disabled in this session."}'; fi`

/**
 * PreInvocation injector. The payload is pre-serialized by the adapter and
 * handed over in the spawn env, so nothing here depends on node, on a temp
 * file, or on agy's state — a per-account HOME is shared by concurrent root and
 * subagent runs, and a payload written into it would leak between them.
 * `invocationNum` is 0-based per model call within a turn, so the guard keeps a
 * single injection even when one turn issues several calls. Both numbers are
 * matched with a trailing delimiter: an unanchored `"initialNumSteps":1` also
 * matches `10` and `199`, which would re-inject on a continuation. The value
 * separator is optional so a pretty-printed payload still matches.
 */
const RULES_INJECT = `S=$(cat); if [ -n "$DSH_AGY_RULES" ] && printf %s "$S" | grep -qE '"invocationNum" *: *0([,}])' && printf %s "$S" | grep -qE '"initialNumSteps" *: *1([,}])'; then printf %s "$DSH_AGY_RULES"; else printf %s '{}'; fi`

/** The hooks this plugin owns inside a managed HOME. */
export function agyHooks(): Record<string, unknown> {
  return {
    'dsh-agy-link': {
      PreToolUse: [
        {
          matcher: 'invoke_subagent|define_subagent|manage_subagents',
          hooks: [{ type: 'command', command: SUBAGENT_GATE }],
        },
      ],
      PreInvocation: [{ type: 'command', command: RULES_INJECT }],
    },
  }
}

/**
 * The PreInvocation payload carrying DSH's global rules into a root agy run, or
 * an empty string when DSH has no global AGENTS.md. Read per spawn so an edit to
 * the file takes effect on the next turn. The text is the adapted AGENTS.md
 * (DSH-only surfaces stripped), so agy never reads instructions for tools it
 * does not have.
 */
export function rootRulesPayload(): string {
  const agents = join(dshHome(), 'AGENTS.md')
  if (!existsSync(agents)) return ''
  return JSON.stringify({ injectSteps: [{ ephemeralMessage: adaptAgentsMd(readFileSync(agents, 'utf8')) }] })
}

/**
 * Every path agy auto-discovers a global rules file from. Both are swept: a file
 * at either one would reach every run, including a subagent run.
 */
const GLOBAL_RULES_PATHS: readonly string[] = [
  join('.gemini', 'GEMINI.md'),
  join('.gemini', 'config', 'GEMINI.md'),
]

const AGY_TOKEN_FILE = join('.gemini', 'antigravity-cli', 'antigravity-oauth-token')

/**
 * HOME the plugin spawns agy with for this account. Isolated pool accounts
 * keep their own directory; the system-HOME account gets a plugin-managed
 * directory so its rules, skills and bridge config never land in the real
 * ~/.gemini (its credential is seeded from there instead).
 *
 * The managed HOME lives INSIDE the pool directory on purpose: pool.json,
 * every isolated account and every managed HOME are then one subtree, so the
 * config-manager sync picks all of them up with a single directory rule
 * instead of two unrelated paths.
 */
export function agyHomeFor(account: ManagedAccount): string {
  if (account.dir !== '') return account.dir
  return join(defaultPoolDir(), 'env', account.id)
}

/**
 * First-use seeding: the system-HOME account's credential is COPIED into the
 * managed HOME (verified safe — agy stays signed in, refreshes only its own
 * copy, and the real HOME's token is left alone). An existing managed token is
 * never overwritten: once the managed HOME refreshes its own token, that copy
 * is the authoritative one.
 */
export function seedAgyHome(home: string, sourceHome: string): void {
  const target = join(home, AGY_TOKEN_FILE)
  if (existsSync(target)) return
  const source = join(sourceHome, AGY_TOKEN_FILE)
  if (!existsSync(source)) return
  mkdirSync(dirname(target), { recursive: true })
  copyFileSync(source, target)
  try {
    chmodSync(target, 0o600)
  } catch {
    // Windows: mode bits unsupported — best effort
  }
}

export interface AgyEnvOptions {
  /** Reverse MCP bridge to publish into the managed HOME; omitted when disabled. */
  bridge?: McpBridge
  /** Real user HOME the managed HOME is seeded from (defaults to the process HOME). */
  sourceHome?: string
}

/**
 * Materialize the plugin-managed agy environment for one account and return
 * its HOME. Idempotent: a file is rewritten only when its bytes change, so the
 * per-spawn call never churns mtimes.
 */
export function syncAgyEnv(account: ManagedAccount, opts: AgyEnvOptions = {}): string {
  const home = agyHomeFor(account)
  // Only a plugin-managed HOME is seeded: an isolated account must never
  // inherit the system credential, or two slots would share one identity.
  if (home !== account.dir) seedAgyHome(home, opts.sourceHome ?? homedir())
  // A rules file must NOT live under this HOME: agy auto-discovers GEMINI.md
  // from $HOME/.gemini AND $HOME/.gemini/config, so a file at either path
  // applies to every run — subagents included. The root run gets its rules
  // through the PreInvocation hook below instead. Both paths are swept, not just
  // the one older plugin versions wrote: a config-manager snapshot from another
  // device can restore a copy to either, and the sync runs before this on boot.
  for (const stale of GLOBAL_RULES_PATHS) {
    const file = join(home, stale)
    if (existsSync(file)) rmSync(file, { force: true })
  }
  writeIfChanged(join(home, '.gemini', 'config', 'hooks.json'), JSON.stringify(agyHooks(), null, 2) + '\n')
  copySkills(join(dshHome(), 'skills'), join(home, '.gemini', 'config', 'skills'))
  if (opts.bridge !== undefined) {
    const file = mcpConfigPath(home)
    writeIfChanged(file, mergeMcpConfig(readIfExists(file), opts.bridge))
    // Plan mode is the only mode that consults permissions.allow ('skip', the
    // default, already passes --dangerously-skip-permissions). Without the rule
    // a plan-mode spawn auto-denies every mcp(dsh-tools) call, and headless mode
    // cannot prompt — so the file is created when agy has not written one yet.
    const settings = join(home, '.gemini', 'antigravity-cli', 'settings.json')
    const next = allowMcpServer(readIfExists(settings) ?? '{}')
    if (next !== null) writeIfChanged(settings, next)
  }
  return home
}

function readIfExists(file: string): string | null {
  return existsSync(file) ? readFileSync(file, 'utf8') : null
}

/** Write only when the content differs — keeps the whole sync mtime-stable. */
function writeIfChanged(file: string, content: string): void {
  if (readIfExists(file) === content) return
  mkdirSync(dirname(file), { recursive: true })
  writeFileSync(file, content, 'utf8')
}

/** Copy every DSH skill (a directory holding a SKILL.md) into agy's own skill dir. */
function copySkills(source: string, dest: string): void {
  if (!existsSync(source)) return
  for (const entry of readdirSync(source, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    const skill = join(source, entry.name)
    if (!existsSync(join(skill, 'SKILL.md'))) continue
    copyTree(skill, join(dest, entry.name))
  }
}

function copyTree(source: string, dest: string): void {
  mkdirSync(dest, { recursive: true })
  for (const entry of readdirSync(source, { withFileTypes: true })) {
    const from = join(source, entry.name)
    const to = join(dest, entry.name)
    if (entry.isSymbolicLink()) copyLink(from, to)
    else if (entry.isDirectory()) copyTree(from, to)
    else copyFileIfChanged(from, to)
  }
}

/**
 * Recreate a symlink instead of following it. Skill packs ship self-links such
 * as `subskills/<name> -> ..`; following one recurses forever, and the
 * copyFileSync fallback dies with ENOTSUP because the target is a directory —
 * which aborted the whole env sync before the MCP config was ever written.
 */
function copyLink(from: string, to: string): void {
  const target = readlinkSync(from)
  // lstatSync must not throw for a dangling link: existsSync() reports false
  // for one, so the link would be recreated on every sync.
  const current = lstatSync(to, { throwIfNoEntry: false })
  if (current?.isSymbolicLink() === true && readlinkSync(to) === target) return
  rmSync(to, { recursive: true, force: true })
  symlinkSync(target, to)
}

function copyFileIfChanged(from: string, to: string): void {
  if (existsSync(to)) {
    const source = statSync(from)
    const target = statSync(to)
    if (source.size === target.size && readFileSync(from).equals(readFileSync(to))) return
  }
  copyFileSync(from, to)
}
