#!/usr/bin/env node
/**
 * Aggregate bundle generator for the dsh-plugins monorepo.
 *
 * An aggregate bundle is a plain carrier package whose cordis.patch.yml is the
 * concatenation of its child plugins' cordis.patch.yml, and whose package.json
 * dependencies pull in every child as a normal semver range. The DSH loader
 * resolves each patch row's `name:` from the profile root, so the children are
 * installed as ordinary dependencies of the aggregate.
 *
 * Usage:
 *   node scripts/aggregate.mjs            # regenerate + write
 *   node scripts/aggregate.mjs --check    # verify only; exit 1 on drift
 *
 * Each aggregate package carries a hand-written aggregate.yml manifest:
 *
 *   patchFrom:
 *     - ../dsh-config-manager     # child patch rows, concatenated in order
 *   deps:
 *     - ../dsh-config-manager     # child package name + version -> dependency
 *
 * Only those two sections exist. A child's own cordis.patch.yml is the single
 * source of truth for its row (id, name, config); the generator never renames
 * or rewrites rows, so a fork that must change its row name edits its own
 * patch file and the aggregate follows.
 *
 * Idempotent: safe to rerun at any time. Writes only the aggregate packages it
 * owns; never touches other packages or git state.
 */
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve as resolvePath } from 'node:path'
import { fileURLToPath } from 'node:url'

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
export const REPO_ROOT = resolvePath(SCRIPT_DIR, '..')

const PATCH_HEADER = [
  '# AUTO-GENERATED by scripts/aggregate.mjs — do not edit',
  '# Derived from this package\'s aggregate.yml; edit that manifest and rerun',
  '# `node scripts/aggregate.mjs`. Each block below is one patchFrom child\'s own',
  '# cordis.patch.yml, reproduced verbatim so the row id/name stay owned by the child.',
]

/** Directories directly under a path (non-recursive, sorted). */
function listSubdirs(dir) {
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter((entry) => {
      try {
        return statSync(join(dir, entry)).isDirectory()
      } catch {
        return false
      }
    })
    .sort()
}

/** Every aggregate package: packages/* carrying an aggregate.yml. */
export function findAggregates(root = REPO_ROOT) {
  return listSubdirs(join(root, 'packages'))
    .map((name) => join(root, 'packages', name))
    .filter((dir) => existsSync(join(dir, 'aggregate.yml')))
    .map((pkgDir) => ({ pkgDir, ymlPath: join(pkgDir, 'aggregate.yml') }))
}

/**
 * Parse the hand-written manifest. YAML subset on purpose: comment and blank
 * lines are skipped, "<key>:" starts a section, "- <value>" belongs to the
 * current section. Unknown sections drop their entries so manifest ordering
 * never matters.
 */
export function parseManifest(text, errors = [], rel = 'aggregate.yml') {
  const manifest = { patchFrom: [], deps: [] }
  let section = null
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim()
    if (!line || line.startsWith('#')) continue
    const sectionMatch = line.match(/^[A-Za-z0-9_-]+:\s*$/)
    if (sectionMatch) {
      section = line.slice(0, -1)
      continue
    }
    if (!(section in manifest)) continue
    const entryMatch = line.match(/^-\s+(.+)$/)
    if (!entryMatch) continue
    manifest[section].push(entryMatch[1].trim().replace(/\s+#.*$/, ''))
  }
  if (manifest.patchFrom.length === 0) errors.push(`${rel}: patchFrom is empty (the aggregate patch would be empty)`)
  return manifest
}

/** Read one child package manifest, failing loudly on a missing/unreadable/private child. */
function readChildPackage(dir, errors, rel) {
  const pkgPath = join(dir, 'package.json')
  if (!existsSync(pkgPath)) {
    errors.push(`${rel}: child has no package.json: ${pkgPath}`)
    return null
  }
  let pkg
  try {
    pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
  } catch (e) {
    errors.push(`${rel}: cannot read ${pkgPath}: ${e.message}`)
    return null
  }
  if (typeof pkg.name !== 'string' || pkg.name === '') {
    errors.push(`${rel}: child ${pkgPath} has no "name"`)
    return null
  }
  if (typeof pkg.version !== 'string' || pkg.version === '') {
    errors.push(`${rel}: child ${pkgPath} has no "version"`)
    return null
  }
  if (pkg.private === true) {
    errors.push(`${rel}: child ${pkg.name} is private and cannot be a published aggregate's dependency`)
    return null
  }
  return pkg
}

/** Render the aggregate cordis.patch.yml: header + each child's patch verbatim under a source header. */
export function renderPatch(blocks) {
  const lines = [...PATCH_HEADER]
  for (const block of blocks) {
    lines.push('', `# from ${block.entry}`, ...block.body)
  }
  return lines.join('\n') + '\n'
}

/**
 * Rebuild the aggregate package.json: every manifest deps entry becomes a
 * dependency pinned to the child's published range (^version), other fields
 * preserved, and dependencies the manifest no longer names are pruned so the
 * generated file has exactly one source.
 */
export function renderPackageJson(pkgText, resolvedDeps) {
  const pkg = JSON.parse(pkgText)
  const next = {}
  for (const { name, version } of [...resolvedDeps].sort((a, b) => a.name.localeCompare(b.name))) {
    next[name] = `^${version}`
  }
  if (Object.keys(next).length) pkg.dependencies = next
  else delete pkg.dependencies
  return JSON.stringify(pkg, null, 2) + '\n'
}

/** Build every aggregate's expected on-disk content; returns { results, errors }. */
export function buildAll(root = REPO_ROOT) {
  const errors = []
  const results = []
  for (const { pkgDir, ymlPath } of findAggregates(root)) {
    const rel = relative(root, pkgDir)
    const manifest = parseManifest(readFileSync(ymlPath, 'utf8'), errors, rel)
    const blocks = []
    const resolvedDeps = []
    const seenNames = new Set()
    for (const entry of manifest.patchFrom) {
      const childDir = resolvePath(pkgDir, entry)
      if (!existsSync(childDir)) {
        errors.push(`${rel}: patchFrom target not found: ${entry}`)
        continue
      }
      const patchPath = join(childDir, 'cordis.patch.yml')
      if (!existsSync(patchPath)) {
        errors.push(`${rel}: patchFrom target has no cordis.patch.yml: ${entry}`)
        continue
      }
      const body = readFileSync(patchPath, 'utf8').replace(/\s+$/, '').split(/\r?\n/)
      if (!body.some((line) => /^\s*- id:/.test(line))) {
        errors.push(`${rel}: no plugin row found in ${relative(root, patchPath)}`)
        continue
      }
      blocks.push({ entry, body })
    }
    for (const entry of manifest.deps) {
      const childDir = resolvePath(pkgDir, entry)
      if (!existsSync(childDir)) {
        errors.push(`${rel}: deps target not found: ${entry}`)
        continue
      }
      const pkg = readChildPackage(childDir, errors, rel)
      if (!pkg) continue
      if (seenNames.has(pkg.name)) {
        errors.push(`${rel}: duplicate deps entry ${pkg.name}`)
        continue
      }
      seenNames.add(pkg.name)
      resolvedDeps.push({ name: pkg.name, version: pkg.version })
    }
    results.push({
      rel,
      patch: renderPatch(blocks),
      pkgJson: renderPackageJson(readFileSync(join(pkgDir, 'package.json'), 'utf8'), resolvedDeps),
      patchPath: join(pkgDir, 'cordis.patch.yml'),
      pkgPath: join(pkgDir, 'package.json'),
      rows: blocks.length,
      deps: resolvedDeps.length,
    })
  }
  return { results, errors }
}

function main(argv) {
  const check = argv.includes('--check')
  const { results, errors } = buildAll()
  if (errors.length) {
    for (const e of errors) console.error(`[aggregate] ERROR ${e}`)
    process.exit(1)
  }
  if (results.length === 0) {
    console.log('[aggregate] no aggregate.yml found; nothing to do.')
    return
  }
  let failed = false
  for (const r of results) {
    if (check) {
      const drift = []
      if (!existsSync(r.patchPath) || readFileSync(r.patchPath, 'utf8') !== r.patch) drift.push(relative(REPO_ROOT, r.patchPath))
      if (!existsSync(r.pkgPath) || readFileSync(r.pkgPath, 'utf8') !== r.pkgJson) drift.push(relative(REPO_ROOT, r.pkgPath))
      if (drift.length) {
        for (const d of drift) console.error(`[aggregate] check: ${d} differs from generated content`)
        failed = true
      } else {
        console.log(`[aggregate] check OK: ${r.rel} (${r.rows} source block(s), ${r.deps} dep(s))`)
      }
      continue
    }
    writeFileSync(r.patchPath, r.patch)
    writeFileSync(r.pkgPath, r.pkgJson)
    console.log(`[aggregate] wrote ${relative(REPO_ROOT, r.patchPath)} (${r.rows} source block(s))`)
    console.log(`[aggregate] wrote ${relative(REPO_ROOT, r.pkgPath)} (${r.deps} dep(s))`)
  }
  if (failed) process.exit(1)
}

if (process.argv[1] && resolvePath(process.argv[1]) === resolvePath(fileURLToPath(import.meta.url))) main(process.argv.slice(2))
